{{- range $name, $spec := .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  secretName: {{ $.Release.Name }}-{{ $name }}
  commonName: {{ $spec.commonName }}
  isCA: {{ $spec.isCA | default false }}
  privateKey:
    algorithm: ECDSA
    size: 256
  subject: {{ $spec.subject | toYaml | nindent 4 }}
  issuerRef:
    name: {{ include "kink.issuerName" $ }}
    kind: Issuer
    group: cert-manager.io
  usages: {{- $spec.usages | toYaml | nindent 4 }}
  dnsNames:
    {{- range $dnsName := ($spec.dnsNames | default (list)) }}
    {{- $result := tpl $dnsName $ | quote }}
    {{- if $result}}
    - {{ $result }}
    {{- end }}
    {{- end }}
---
{{- end }}
