global:
  clusterHost: kubernetes.local


certificates:
  admin:
    commonName: admin
    subject:
      organizations:
        - system:masters

#    usages:
#      - digital signature
#      - key encipherment
#      - server auth
#      - client auth

kube-apiserver:
  service:
    type: NodePort
    ports:
      - name: kube-apiserver
        port: 6443
        targetPort: 6443
        nodePort: 30443
