apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.fullname" . }}-service-accounts
spec:
  secretName: {{ include "common.fullname" . }}-service-accounts
  commonName: service-accounts
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "common.release.fullname" . }}
    kind: Issuer
    group: cert-manager.io