apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.release.fullname" . }}
spec:
  isCA: true
  commonName: CA
  secretName: {{ include "common.release.fullname" . }}-root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "common.fullname" . }}-bootstrap
    kind: Issuer
    group: cert-manager.io

