apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "common.fullname" . }}-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "common.release.fullname" . }}
spec:
  ca:
    secretName: {{ include "common.release.fullname" . }}-root-ca