# This job creates kubeconfig you could from your computer.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}
spec:
  template:
    spec:
      containers:
        - name: {{ include "common.name" . }}
          image: {{ include "common.image" . }}
          command:
            - /bin/sh
            - -c
            - |-
              set -e
              kubectl config set-cluster {{ include "common.release.fullname" . }} \
              --certificate-authority=/var/lib/kubernetes/ca.crt \
              --embed-certs=true \
              --server=https://{{ include "common.fullname" (get .Subcharts "kube-apiserver") }}:6443 \
              --kubeconfig=admin.kubeconfig

              kubectl config set-credentials admin \
              --client-certificate=/var/lib/kubernetes/tls.crt \
              --client-key=/var/lib/kubernetes/tls.key \
              --embed-certs=true \
              --kubeconfig=admin.kubeconfig

              kubectl config set-context default \
              --cluster={{ include "common.release.fullname" . }} \
              --user=admin \
              --kubeconfig=admin.kubeconfig

              kubectl config use-context default \
              --kubeconfig=admin.kubeconfig

              kubectl create --dry-run=client -o yaml secret generic {{ include "common.release.fullname" . }}-admin-kubeconfig --from-file=config=admin.kubeconfig | kubectl apply -f -
          workingDir: /wd
          volumeMounts:
            - mountPath: /var/lib/kubernetes
              name: kubernetes

            - mountPath: /wd
              name: wd
      serviceAccountName: {{ include "common.fullname" . }}
      restartPolicy: OnFailure
      volumes:
        - name: wd
          emptyDir: {}
        - name: kubernetes
          projected:
            sources:
              - secret:
                  items:
                    - path: tls.key
                      key: tls.key
                    - path: tls.crt
                      key: tls.crt
                  name: {{ include "common.fullname" . }}-admin
              - secret:
                  name: {{ include "common.release.fullname" . }}-root-ca
                  items:
                    - path: ca.crt
                      key: ca.crt

